version: '3'
services:
  f1-racing-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
    restart: always
