version: '3'

services:
  flask-app:
    build: .
    container_name: python-flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
